services:
  server:
    container_name: server
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    env_file:
      - ./server/.env
      - ./.env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FLASK_DB_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    command: gunicorn wsgi:app -b 0.0.0.0:8000 --timeout 60 --workers 3
    dns: 8.8.8.8
    ports:
      - "8000:8000"
    networks:
      - legal_assistant_network
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:8000/healthcheck/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    extra_hosts:
      - "host.docker.internal:host-gateway"

  telegram-client:
    container_name: telegram-client
    build:
      context: ./
      dockerfile: ./telegram_client/Dockerfile
    env_file:
      - ./telegram_client/.env
    environment:
      - SERVER_HOST=http://server:8000
    command: uv run asgi.py
    dns: 8.8.8.8
    depends_on:
      server:
          condition: service_healthy
    networks:
      - legal_assistant_network

  redis:
    container_name: redis
    image: redis:8.2.3-alpine
    ports:
      - "6380:6379"
    networks:
      - legal_assistant_network
    healthcheck:
      test: redis-cli ping

  postgres:
    container_name: legal-assistant-postgres
    image: postgres:15
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - legal_assistant_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  legal_assistant_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
